blank_issues_enabled: false
contact_links:
  - name: Support / Questions
    url: https://github.com/qut-dmrc/academicOps/discussions
    about: Please use discussions for support and general questions.
